### ISSUE TITLE
Can I specify the aws_region within the logging yaml file?

### ISSUE THREAD

**Issue by dibog** [kislyuk/watchtower#175]
First off, thanks for this library. I'm playing around and it looks really nice.
But I have a question. It seems that watchtower requires the aws_region. Would it be possible
to specify the region via the logging yaml file from the example: https://github.com/kislyuk/watchtower#examples-python-logging-config

Something like: 
```
watchtower:
    class: watchtower.CloudWatchLogHandler
    region: eu-central-1
    formatter: json
    level: DEBUG
    log_group_name: watchtower
    log_stream_name: "{logger_name}-{strftime:%y-%m-%d}"
    send_interval: 10
    create_log_group: False
```

I know that you can specify the region via the  boto3.client. But I would like to keep my main program free form
such "logging details".

Thanks!
