### ISSUE TITLE
No data sent

### ISSUE THREAD

**Issue by astronouth7303** [kislyuk/watchtower#25]
I'm using watchtower to send up all my logs from my django app. Watchtower successfully makes log groups, but never creates any streams nor submits any data.

No errors are logged anywhere I can find them. (Not in the log I configured or stderr logged by apache.)

**Comment by kislyuk** [comment]
Please provide more information, either a reduced test case or a snippet of the code for your loggers.

**Comment by astronouth7303** [comment]
Here's my `LOGGING` setting from my Django app.

```python
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/opt/python/log/app/debug.log',
            'formatter': 'file',
        },
        'watchtower': {
            'level': 'DEBUG',
            'class': 'watchtower.CloudWatchLogHandler',
            'formatter': 'file',
            'log_group': os.environ.get('AWS_STACK_NAME', 'innocence'),
            'use_queues': False,
        }
    },
    'formatters': {
        'file': {
            'format': '%(asctime)s\t%(name)s\t%(levelname)s\t%(message)s',
        },
    },
    'loggers': {
        '': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'boto': {
            'level': 'INFO',
        },
        'botocore': {
            'level': 'INFO',
        },
    },
}
```

And a snippet from my CloudFormation template setting permissions:

```yaml
  WebServerRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Statement: 
          - Effect: Allow
            Principal: 
              Service: 
                - !FindInMap [Region2Principal, !Ref "AWS::Region", EC2Principal]
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkEnhancedHealth"
        - "arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkService"
      Path: "/"
  WebServerRolePolicy: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: WebServerRole
      PolicyDocument: 
        Statement: 
          - Effect: Allow
            NotAction: "iam:*"
            Resource: "*"
          - Effect: Allow
            Action: 
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
              - "logs:DescribeLogStreams"
            Resource: 
              - "arn:aws:logs:*:*:*"
      Roles: 
        - !Ref WebServerRole
```
