### ISSUE TITLE
No Log Events in Cloudwatch

### ISSUE THREAD

**Issue by FreddyFFM** [kislyuk/watchtower#49]
Hi,

maybe it's not a real iussue, but I tried using watchtower to send my Log-Events from Python Scripts to CloudWatch and they are not showing up in CloudWatch Console.

I have the following test-script:

```
import logging 
import logging.config 
import yaml 

#LogConfig
with open('watchtower_config.yml', 'r') as log_config:
    config_yml = log_config.read()
    config_dict = yaml.load(config_yml)
    logging.config.dictConfig(config_dict)
    logger = logging.getLogger('root')  
    
try:
    logger.debug("TEST")
except Exception, e:
    print(str(e))
```

With a config file mentioned in the docs

```
version: 1
formatters:
    json:
        format: "[%(asctime)s] %(process)d %(levelname)s %(name)s:%(funcName)s:%(lineno)s - %(message)s"
    plaintext:
        format: "[%(asctime)s] %(process)d %(levelname)s %(name)s:%(funcName)s:%(lineno)s - %(message)s"      
handlers:
    console:
        (): logging.StreamHandler
        level: DEBUG
        formatter: plaintext
        stream: sys.stdout
    watchtower:
        formatter: json
        level: DEBUG
        (): watchtower.CloudWatchLogHandler
        log_group: ods-dwh-aql-load
        stream_name:  aql-load
        boto3_profile_name: aqllogger
        send_interval: 1
        create_log_group: False
loggers:
    root:
        handlers: [console, watchtower]
    boto:
        handlers: [console]
    boto3:
        handlers: [console]
    botocore:
        handlers: [console]
    requests:
        handlers: [console]
```

Profile is set correctly and policies were tested with policies-simulator.
As I don not get an error-message it's hard to debug. What am I missing?

Regards

**Comment by dmitrysmirnovfinnair** [comment]
I'm not sure if this is going to help you, but it did help me. According to official docs (same applies to both 2.7 and 3.6, for example): https://docs.python.org/2/library/logging.config.html#logging-config-dictschema in the logging.config.dictConfig the `root` logger is announced either at the top level of config, or if in `loggers`, it is referenced as empty string. For example:
```
version: 1
formatters:
    json:
        format: "[%(asctime)s] %(process)d %(levelname)s %(name)s:%(funcName)s:%(lineno)s - %(message)s"
    plaintext:
        format: "[%(asctime)s] %(process)d %(levelname)s %(name)s:%(funcName)s:%(lineno)s - %(message)s"      
handlers:
    console:
        (): logging.StreamHandler
        level: DEBUG
        formatter: plaintext
        stream: sys.stdout
    watchtower:
        formatter: json
        level: DEBUG
        (): watchtower.CloudWatchLogHandler
        log_group: ods-dwh-aql-load
        stream_name:  aql-load
        boto3_profile_name: aqllogger
        send_interval: 1
        create_log_group: False
loggers:
    '':
        handlers: [console, watchtower]
    boto:
        handlers: [console]
    boto3:
        handlers: [console]
    botocore:
        handlers: [console]
    requests:
        handlers: [console]
```

I was having a similar problem, and this change unbroke everything for me. To add detail, I was using logging directly, without taking specific loggers. E.g. `logging.info("blahblahblah")` instead of `logger = logging.getLogger()` and then logging anything.
