### ISSUE TITLE
Error on trying to log with yml file.

### ISSUE THREAD

**Issue by Shivakishore14** [kislyuk/watchtower#53]
Error
```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 880, in emit
    stream.write(fs % msg)
AttributeError: 'str' object has no attribute 'write'
```
my yml file
```
# Default AWS Config
version: 1
formatters:
    json:
        format: "[%(asctime)s] %(process)d %(levelname)s %(name)s:%(funcName)s:%(lineno)s - %(message)s"
    plaintext:
        format: "[%(asctime)s] %(process)d %(levelname)s %(name)s:%(funcName)s:%(lineno)s - %(message)s"
handlers:
    console:
        (): logging.StreamHandler
        level: DEBUG
        formatter: plaintext
        stream: sys.stdout
    watchtower:
        formatter: json
        level: DEBUG
        (): watchtower.CloudWatchLogHandler
        log_group: watchtower
        stream_name: test
        send_interval: 1
        create_log_group: True
loggers:
    root:
        handlers: [watchtower]
    boto:
        handlers: [console]
    boto3:
        handlers: [console]
    botocore:
        handlers: [console]
    requests:
        handlers: [console]
```
